export enum interviewProfileStatus {
    OPEN = 'OPEN',
    PENDING = 'PENDING',
    SELECTED = 'SELECTED',
    REJECTED = 'REJECTED',
    SCREENING = 'SCREENING',
    HR_INTERVIEW = 'HR INTERVIEW',
    TECHNICAL_INTERVIEW = 'TECHNICAL INTERVIEW',
    CLIENT_INTERVIEW = 'CLIENT INTERVIEW'
}

export enum interviewStatus {
    OPEN = 'OPEN',
    PENDING = 'PENDING',
    SELECTED = 'SELECTED',
    REJECTED = 'REJECTED'
}

export enum InterViewType {
    OPEN = 'OPEN',
    SCREENING = 'SCREENING',
    HR_INTERVIEW = 'HR INTERVIEW',
    TECHNICAL_INTERVIEW = 'TECHNICAL INTERVIEW',
    CLIENT_INTERVIEW = 'CLIENT INTERVIEW'
}
