export enum DocumentTypeEnum {
    Company_logo = 'Company Logo',
    Company_Presentation = 'Company Presentation',
    Company_Brochar = 'Company Brochar',
    Leave_ploicy = 'Leave Policy',
    Late_minutes_policy = 'Late Minutes Policy',
    Attendance_policy = 'Attendance Policy',
    Payroll_calculations = 'Payroll Calculations',
    TDS_Certificate = 'TDS Certificate',
    Labour_certificate = 'Labour Certificate',
    Company_registration = 'Company Registration',
    Organizational_Structure = 'Organizational Structure',
    Code_of_Conduct_And_Ethics = 'Code of Conduct & Ethics',
    Safety_And_Security = 'Safety & Security',
    Departmental_SOPs = 'Departmental SOPs',
    Onboarding_And_Offboarding_Proces = 'Onboarding & Offboarding Process',
    Employee_Training_Manuals = 'Employee Training Manuals',
    Legal_And_Compliance = 'Legal & Compliance',
    Audit_And_Risk_Management_Reports = 'Audit & Risk Management Reports',
}